name: Deploy Next.js App

on:
  push:
    branches:
      - main  # Run workflow on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use your required Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: .next  # Uploads build files
